import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-securities-lending-revenue-share-audit",
  "engine": "recovery",
  "title": "Securities Lending Revenue-Share Audit",
  "shortTitle": "Securities Lending Revenue-Share Audit",
  "tagline": "Rebuild securities-lending economics and recover missing borrower spread, collateral income, and contractual revenue share.",
  "industry": "Investment Operations",
  "buyer": "Asset owners, custodians, and fund managers",
  "uiPort": 4670,
  "apiPort": 5670,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Securities Lending Revenue-Share Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash in one accountable workflow. Rebuild securities-lending economics and recover missing borrower spread, collateral income, and contractual revenue share.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Securities Lending Revenue-Share Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("agency-agreement-library","SLR01","Agency agreement library","Execute agency agreement library using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed agency agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Agency agreement library Reference","text","SLR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("eligible-security-inventory","SLR02","Eligible security inventory","Execute eligible security inventory using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed eligible security inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Eligible security inventory Reference","text","SLR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("loan-transaction-ingestion","SLR03","Loan transaction ingestion","Execute loan transaction ingestion using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed loan transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Loan transaction ingestion Reference","text","SLR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("collateral-balance-validation","SLR04","Collateral balance validation","Execute collateral balance validation using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed collateral balance validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Collateral balance validation Reference","text","SLR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("borrower-fee-calculation","SLR05","Borrower fee calculation","Execute borrower fee calculation using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed borrower fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Borrower fee calculation Reference","text","SLR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("rebate-rate-calculation","SLR06","Rebate rate calculation","Execute rebate rate calculation using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed rebate rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Rebate rate calculation Reference","text","SLR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("collateral-reinvestment-income","SLR07","Collateral reinvestment income","Execute collateral reinvestment income using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed collateral reinvestment income decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Collateral reinvestment income Reference","text","SLR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("specials-premium-analysis","SLR08","Specials premium analysis","Execute specials premium analysis using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed specials premium analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Specials premium analysis Reference","text","SLR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("indemnification-fee-control","SLR09","Indemnification fee control","Execute indemnification fee control using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed indemnification fee control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Indemnification fee control Reference","text","SLR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("revenue-share-calculation","SLR10","Revenue share calculation","Execute revenue share calculation using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed revenue share calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Revenue share calculation Reference","text","SLR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("custodian-statement-audit","SLR11","Custodian statement audit","Execute custodian statement audit using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed custodian statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Custodian statement audit Reference","text","SLR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("corporate-action-treatment","SLR12","Corporate action treatment","Execute corporate action treatment using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed corporate action treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Corporate action treatment Reference","text","SLR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("exception-dispute-workflow","SLR13","Exception dispute workflow","Execute exception dispute workflow using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed exception dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Exception dispute workflow Reference","text","SLR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("cash-reconciliation","SLR14","Cash reconciliation","Execute cash reconciliation using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Cash reconciliation Reference","text","SLR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]}),
feature("program-security-analytics","SLR15","Program security analytics","Execute program security analytics using agency agreements, eligible portfolios, loans, collateral, rebate rates, investment income, borrower fees, indemnification fees, revenue shares, statements, and cash.","Produce a governed program security analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Custodian / Lending Program","text","Custodian / Lending Program · Standard Case"],["caseReference","Program security analytics Reference","text","SLR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",878750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1063288],["domainDriver","Loan Type","select","General collateral",["General collateral","Special","Term loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agency agreement library case","Eligible security inventory case","Loan transaction ingestion case","Collateral balance validation case","Borrower fee calculation case"]})
]);
